artifact_uri: file:///kaggle/working/mlruns/798868638505641586/7d8cde26524c4e1fa9c9ba1f50aaea44/artifacts
end_time: null
entry_point_name: ''
experiment_id: '798868638505641586'
lifecycle_stage: active
run_id: 7d8cde26524c4e1fa9c9ba1f50aaea44
run_name: valuable-fox-713
run_uuid: 7d8cde26524c4e1fa9c9ba1f50aaea44
source_name: ''
source_type: 4
source_version: ''
start_time: 1724087981710
status: 1
tags: []
user_id: unknown
