artifact_uri: file:///kaggle/working/mlruns/798868638505641586/e76bac624ea34ccfabcc92f9d74da56b/artifacts
end_time: null
entry_point_name: ''
experiment_id: '798868638505641586'
lifecycle_stage: active
run_id: e76bac624ea34ccfabcc92f9d74da56b
run_name: calm-wasp-784
run_uuid: e76bac624ea34ccfabcc92f9d74da56b
source_name: ''
source_type: 4
source_version: ''
start_time: 1724088065139
status: 1
tags: []
user_id: unknown
