artifact_uri: file:///kaggle/working/mlruns/798868638505641586/96203a46ccdb4c4c8ce7a6bfbd8304b8/artifacts
end_time: null
entry_point_name: ''
experiment_id: '798868638505641586'
lifecycle_stage: active
run_id: 96203a46ccdb4c4c8ce7a6bfbd8304b8
run_name: upbeat-pug-96
run_uuid: 96203a46ccdb4c4c8ce7a6bfbd8304b8
source_name: ''
source_type: 4
source_version: ''
start_time: 1724088043905
status: 1
tags: []
user_id: unknown
